### PR TITLE
Bump python-dateutil from v2.8.1 to v2.8.2

### PR DESCRIPTION
**Pull request by bmos**
Pandas requires python-dateutil 2.8.2 since at least pandas v2.0.0, with pandas v3.0.0 coming soon.
It would be helpful to be able to be able to use parsons with pandas.

### CODE REVIEW

**Comment by bmos** [comment]
I see that you have dependabot set up, so I'm not sure why it didn't make a PR for this...

**Comment by bmos** [comment]
It appears that the only thing dateutil is used for is the parser submodule:
https://github.com/search?q=repo%3Amove-coop%2Fparsons+dateutil&type=code

This is touched in the 2.8.2 update:
https://github.com/dateutil/dateutil/releases/tag/2.8.2

**Comment by bmos** [comment]
This is mentioned also in #794

**Review by shaunagm — APPROVED** [review]
sorry for the delay responding!

**Pull request merged**
