### PR TITLE
add script

### PR DESCRIPTION
**Pull request by sharinetmc**

### CODE REVIEW

**Review by shaunagm — CHANGES_REQUESTED** [review]
This looks good - the only issue is the linting. Did you run Black?

**Review by shaunagm — CHANGES_REQUESTED** [review]
Looks like linting is still failing?

**Comment by sharinetmc** [comment]
Hmm...interesting. I just ran it again and it said that the file was left unchanged.

**Comment by shaunagm** [comment]
Can you share the full output of the Black command, as well as the location you're running the command from?

**Comment by sharinetmc** [comment]
(parsons) ➜  parsons git:(sample_ngpvan_printed_list) black useful_resources/sample_code/ngpvan_sample_printedlist.py
All done! ✨ 🍰 ✨
1 file left unchanged.

**Comment by shaunagm** [comment]
So the instructions for how to use Black in the docs are wrong, whoops. Can you try `black --check parsons/ test/ useful_resources/`

**Comment by shaunagm** [comment]
Thanks for the help @bmos but this PR is now including 3 extra files which it shouldn't need to touch. Any idea why/how to fix?

**Comment by bmos** [comment]
Afaik that is because it was needed to get the linting check to pass. You can see the checks on the two commits in my PR.

**Comment by bmos** [comment]
Now the issue is probably the longer length target.

**Comment by shaunagm** [comment]
It's probably easier for Sharine to just redo with a new PR off the most recent main branch. It's easy enough since it's a single file, and then she can run Black which will use whatever the current standards are.

**Pull request closed without merging**
