### PR TITLE
Add pre-commit hook config to run flake8 and black on commit

### LINKED ISSUE #863: Feature Request: Automatically run black and flake8 using pre-commits
## Detailed Description
Implement something similar to [this tutorial](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/) to automatically run black and flake8 using pre-commits.

## Context
I've noticed that often times when contributors open pull requests, the automated tests will fail because it fails the black and/or flake8 test. This issue can be mitigated by automatically running black and flake8 via pre-commits

## Possible Implementation
Something similar to [this tutorial](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/)

## Priority
Low priority, nice-to-have

### PR DESCRIPTION
**Pull request by austinweisgrau**
Notes added to README on how to install and set up

Resolves #863

### CODE REVIEW

**Comment by Jason94** [comment]
@austinweisgrau Will this actually reformat the code in the commit? Or will it just block the PR if it fails to pass the formatter?

**Comment by austinweisgrau** [comment]
It will reformat and block the commit of anything doesn't line up. The changes need to be manually staged. If there are no changes needed, the commit goes through.

**Comment by Jason94** [comment]
> It will reformat and block the commit if anything doesn't line up. The changes need to be manually staged. If there are no changes needed, the commit goes through.

I see. Not going to lie, I thought we already enforced flake8 and black formatting. Maybe that's just on PR, not on commit? @shaunagm? Either way, thanks for setting this up!

**Comment by austinweisgrau** [comment]
We enforce it for a PR to be able to merge, but otherwise it's just part of
the suite of CI tests, so it's possible to commit and push code that is in
violation. Pre-commit hooks are a tool that enforce earlier on, which can
be helpful. Similar to setting up lint-on-save in an IDE, it's just another
layer to help developers out. If developers don't install pre-commit, it
won't be in effect for them. So it's sort of ultimately up to the
individual developer, unlike linting in the CI layer.

**Comment by shaunagm** [comment]
@austinweisgrau I've never personally used pre-commit hooks, what would the experience be like for someone who has them set up?

**Comment by austinweisgrau** [comment]
Pre-commit can be a little annoying if it has slight disagreements with the linter in the IDE or CI. It shouldn't really happen and should theoretically be simple to line up configurations to prevent it, but I've ran into some issues with this at times.

**Comment by austinweisgrau** [comment]
The experience is:

Setup:
- Run `pip install pre-commit` and `pre-commit install`

Thereafter:
When you run `git commit`, pre-commit will run black and flake8 on your staged code at that time and you won't be able to commit if anything doesn't line up. Fixes will be automatically made, so you can run `git add . && git commit ...` at that time. If you have linting run automatically on save in your IDE, this should never come up and the only difference you'll notice is that git takes an extra second or so to run `git commit` then otherwise.

**Comment by austinweisgrau** [comment]
Personally I'm sort of neutral-positive on whether pre-commit is useful to add, but I had a setup ready and saw the issue come in so I figured I'd submit the PR. It's nice to have extra layers to help keep code linted, but with linting in CI this is pretty much taken care of at the repo-level. And I figure most people who are going to pay enough attention to install and set up pre-commit probably are also inclined to set up linting on save in their IDE, so it's potentially a little redundant.

**Comment by crayolakat** [comment]
I created the issue because I saw several people fail the automated tests when creating a PR because of linting/formatting issues, then having to go back and change fix it. Examples:

- https://github.com/move-coop/parsons/pull/859
- https://github.com/move-coop/parsons/pull/834

I think having this pre-commit would help prevent the extra step of having to go back and fix something after submitting a PR

**Comment by Jason94** [comment]
That makes sense to me. Might as well give people as much heads up as possible. It could also save compute time running the CI/CD.

**Comment by shaunagm** [comment]
Austin, would you be willing to write all this up as a very short guide for the website that we can link people to? It doesn't have to be much fancier than what you've currently written but it would be good to have it in one place we can link people to. I think many of the people who might be interested in using this will not have used git pre-commit hooks before and could use a little extra handholding (myself included).

Alternatively I can write it up and you can review and make sure I haven't garbled anything, but I wouldn't be able to get to that until next week at the earliest.

**Comment by austinweisgrau** [comment]
How's this? https://docs.google.com/document/d/186a8JB4q4fOZYYJoZV5EntWd9M4bEKg1WCREC4ydHCI/edit

**Comment by shaunagm** [comment]
Looks great! If someone else gets a chance to test this setup locally and gives the thumbs up, I will merge this (and add Austin's guidance to the website guides). Otherwise I can test it locally next week.

**Comment by crayolakat** [comment]
I can test!

**Comment by crayolakat** [comment]
I tested and the instructions are very clear to easy to follow. Thank you Austin!

**Review by crayolakat — APPROVED** [review]

**Pull request merged**
