### PR TITLE
Updates to ActionKit, S3, and NGPVan

### PR DESCRIPTION
**Pull request by crayolakat**
1. Add `cancel_orderrecurring` and `update_paymenttoken` functions to ActionKit connector
2. Add `use_env_token` parameter to S3 initializer
3. Add ContactNotes class to NGPVan

### CODE REVIEW

**Review by shaunagm — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing! Overall this looks great—my only question is around test coverage. Only one of the three new ActionKit methods has a test, and the new NGPVAN class has two methods, neither of which have tests. Is there a reason not to include tests for these things?

**Comment by crayolakat** [comment]
Hey @shaunagm , no reason not to have tests. I can add them

**Comment by shaunagm** [comment]
Thank you!

**Comment by crayolakat** [comment]
Hey @shaunagm , I added the tests

**Review by shaunagm — APPROVED** [review]

**Comment by shaunagm** [comment]
Awesome, thank you @crayolakat

**Pull request merged**
