### PR TITLE
NewMode - Add bulk `targets` endpoint

### PR DESCRIPTION
**Pull request by IanRFerguson**
This PR adds an additional `GET` request to the NewMode client that allows ALL targets to be queried and returned as a table. The addition of this function will give Parsons users flexibility in their API requests to NewMode, as they may be interested in exploring target data broadly and across outreaches.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204935310402358

### CODE REVIEW

**Comment by willyraedy** [comment]
@ydamit looks like there might be some linting / formatting errors from the action builder connector. Would you mind taking a look at that so we can get the build to run here?

**Comment by ydamit** [comment]
@willyraedy , I'll do my best! Am I using criteria from black or flake8?

**Comment by willyraedy** [comment]
> @willyraedy , I'll do my best! Am I using criteria from black or flake8?

If you click the "Details" link in the build step above, it should show you the errors. 

image

**Comment by shaunagm** [comment]
If you update your branch, it should get rid of those linting errors since they've been fixed on `main` as of this morning.

**Comment by ydamit** [comment]
@willyraedy , gotcha. So it sounds like we're just moving over to black, since it looks like part of the issue is that some of the docstrings that go long are decorated with `noqa` for flake8 purposes, but black doesn't seem to like that?

**Comment by ydamit** [comment]
Oh nevermind, then!

**Comment by willyraedy** [comment]
@IanRFerguson did you see that? Sounds like you just need to re-merge latest from main here

**Comment by IanRFerguson** [comment]
@shaunagm @willyraedy Checks passing! ready for another look when y'all have time

**Review by willyraedy — APPROVED** [review]
LGTM

**Pull request merged**
