### PR TITLE
Remove entity from campaign method

### PR DESCRIPTION
**Pull request by ydamit**
Action Builder's API allows using the DELETE verb to remove entity records from campaigns. The test isn't a very meaningful one, but I guess something is better than nothing!

### CODE REVIEW

**Comment by shaunagm** [comment]
Sorry about the gmail test failure @ydamit - it's suddenly happening to all our open PRs and we're struggling to figure out why.

**Comment by ydamit** [comment]
> Sorry about the gmail test failure @ydamit - it's suddenly happening to all our open PRs and we're struggling to figure out why.

No worries, @shaunagm ! I figured as much.

**Comment by bmos** [comment]
If someone reruns the checks on this after updating the branch from main, it should pass now.

**Review by shaunagm — APPROVED** [review]
lgtm

**Pull request merged**
