### PR TITLE
feat: add Nation Builder Connector

### PR DESCRIPTION
**Pull request by gcollazo**
This PR adds a new [Nation Builder](https://nationbuilder.com/developers) connector.

The connector implements the following public methods:

- `get_people`: make all necessary HTTP request to get all people and return a `Table`. If a request fails, it will wait 30 seconds and keep trying until it fetches everything.
- `update_person`: update a person by their Nation Builder `id`.
- `upsert_person`: update or create a person.

## Examples

The following examples help illustrate the API usage.

```python
from dotenv import load_dotenv

from parsons.nation_builder.nation_builder import NationBuilder

load_dotenv()

nb = NationBuilder()

# get all people and return a Table
people_table = nb.get_people()
people_table.to_csv("nbexport.csv")

# update person by id
data = {"email": "foo@example.com", "tags": ["foo", "bar"]}
updated_person_1 = nb.update_person("123456789", data)

# update or create a person
data = {"email": "foo@example.com", "tags": ["dogs", "cats"]}
created, person = nb.upsert_person(data)

if created:
    print("Person created:", person)
else:
    print("Person updated:", person)
```

### CODE REVIEW

**Review by shaunagm — CHANGES_REQUESTED** [review]
As I mentioned in Slack, this needs documentation (see an [example here](https://move-coop.github.io/parsons/html/stable/action_network.html)). Do you know how hard it is to become a certified developer? I'd love to be able to do a live test but if that's too much of a hassle we can figure something else out.

**Comment by gcollazo** [comment]
Just added the necessary docs using the ActBlue page as a template. I think it's complete and clear but let me know if something else is needed.

We can schedule a quick call and I can run a few test scenarios using our live NB account. I'm on Slack so you can contact me there to coordinate.

We have not explored becoming certified developers since what we are building is for our own internal use. I have a weekly meeting with NB I will bring that up and let you know.

The CI failure looks unrelated to this PR.

**Review by shaunagm — CHANGES_REQUESTED** [review]
Hi Giovanni, just making a note that once you add the mock tests, we should be good to merge.

**Comment by gcollazo** [comment]
@shaunagm just added the additional tests using fixtures. Please do let me know if you need additional changes.

**Review by shaunagm — APPROVED** [review]
Looks good to me!

**Pull request merged**
