### PR TITLE
Van connector docs

### LINKED ISSUE #426: Fix "note" display in VAN connector docs
The formatting of some of the note displays in the VAN connector are off.

This is what it looks like:

Screenshot from 2020-10-01 16-47-43

This is what it should look like:

Screenshot from 2020-10-01 16-47-29

If whoever fixes this skims through the other connectors looking for similar problems, that'd be great, but just fixing the VAN connector may be enough.

**Edited to add**: it looks like the notes also reference an `email_address` variable but the docstrings only mention an `email` parameter, we should check which is valid.

Another issue to fix with the VAN docs ("support" misspelled, plus sentence without ending):

Screenshot from 2020-10-01 19-10-02

### PR DESCRIPTION
**Pull request by Tomiiwa**
Fixes #426

### CODE REVIEW

**Comment by shaunagm** [comment]
You fixed it, thank you! A couple notes before we can merge.

1) There's a weird visual artefact on the changed lines. Where the sentence has gray background instead of blue like the rest of the note. I think to fix it, there needs to be a space between the first sentence and the list:

Screenshot from 2022-03-30 12-44-30

2) You fixed the misspelled "support" (thank you!) but the unfinished sentence is still there. It should be "Please direct any questions to the Parsons team via the issue tracker or Slack."

3) Can you remove the other files and keep only `ngpvan.rst` and `people.py`? The other files were, I think, accidentally included.

Thank you again!

**Comment by shaunagm** [comment]
You fixed it, thank you! A couple notes before we can merge.

1) There's a weird visual artefact on the changed lines. Where the sentence has gray background instead of blue like the rest of the note. I think to fix it, there needs to be a space between the first sentence and the list:

Screenshot from 2022-03-30 12-44-30

2) You fixed the misspelled "support" (thank you!) but the unfinished sentence is still there. It should be "Please direct any questions to the Parsons team via the issue tracker or Slack."

3) Can you remove the other files and keep only `ngpvan.rst` and `people.py`? The other files were, I think, accidentally included.

Thank you again!

**Review by shaunagm — CHANGES_REQUESTED** [review]
See this comment for requested changes:
https://github.com/move-coop/parsons/pull/650#issuecomment-1083380454

**Comment by Tomiiwa** [comment]
Done

**Review by shaunagm — APPROVED** [review]

**Comment by shaunagm** [comment]
All right, looks good. I'll just remove the extra files from the PR and then merge.

**Comment by shaunagm** [comment]
Thank you @Tomiiwa!

**Pull request merged**
