### PR TITLE
feat(Table): Add use_petl method

### PR DESCRIPTION
**Pull request by dannyboy15**
Add a method that exposes the petl functions to `parsons.Table`.

### CODE REVIEW

**Comment by jburchard** [comment]
Fwiw, I like the idea of clearly defined method. The `Table.table` will still exist. Would it be possible to update [this](https://move-coop.github.io/parsons/html/table.html#petl) documentation (show that you can do it both ways) as part of the PR to link to the new method?

**Comment by dannyboy15** [comment]
@SorenSpicknall, This is more of a convenience for using `petl` functions. It allows for functions to be called directly on the `parsons.Table` as oppose to having to reassign it to the underlying `parsons.Table.table`.

Instead of this:

```python
import petl
...

tbl = Table()
tbl.table = petl.skipcomments(tbl.table, '#')
```

you would be able to do something like this

```python
tbl = Table()
tbl.use_petl('skipcomments', '#', update_table=True)
```

@jburchard, yeah I can update the docs

**Comment by SorenSpicknall** [comment]
With the docs changes, I'm in support of merging this. It makes sense to do as a shortcut to using petl functions, for sure.

**Review by SorenSpicknall — APPROVED** [review]
Looks ready to go for me!

**Pull request merged**
