### PR TITLE
updated parakimo to latest

### PR DESCRIPTION
**Pull request by bzupnick**
updating the `parakimo` package to `2.10.4` to get a fix of theirs to solve issue https://github.com/move-coop/parsons/issues/683

### CODE REVIEW

**Comment by shaunagm** [comment]
I'm not sure that updating to 2.10.4 will solve the issue. It looks like it was [cut 21 days ago](https://github.com/paramiko/paramiko/releases/tag/2.10.4) and the fix to remove blowfish [merged the day after](https://github.com/paramiko/paramiko/commits/main).

**Comment by bzupnick** [comment]
Oh you're right!! I (wrongly) assumed that their merged PRs will be included in the latest release 🤦 .

I'll subscribe to their repo for the next release so I'll get a push-notification on when it gets release and amend this PR

**Comment by bzupnick** [comment]
Okay. They cut a new version (`2.11.0`) and [in the changelog](https://www.paramiko.org/changelog.html) for this version they wrote:

```
Recent versions of Cryptography have deprecated Blowfish algorithm support; in lieu of an easy method for users to remove it from the list of algorithms Paramiko tries to import and use, we’ve decided to remove it from our “preferred algorithms” list. This will both discourage use of a weak algorithm, and avoid warnings. Credit for report/patch goes to Mike Roest.
```

**Review by shaunagm — APPROVED** [review]
looks good!

**Pull request merged**
