### PR TITLE
Revert "Docs general cleanup (#415)"

### PR DESCRIPTION
**Pull request by shaunagm**
This reverts commit 049ab3333650748dd7f19a4dca221f084724bd8c for reasons discussed here: https://github.com/move-coop/parsons/issues/419

### CODE REVIEW

**Review by eliotst — APPROVED** [review]

**Review by eliotst — CHANGES_REQUESTED** [review]
There are test failures.

**Comment by eliotst** [comment]
The test failures seem like they are the linting errors on master fixed by #418

**Comment by shaunagm** [comment]
Issue is the the linting from your PR that merged after the one this is reverting.  I'm not sure if you can rebase a revert PR, I've never tried it.

**Comment by eliotst** [comment]
Can we close and reopen now that #418 is merged?

**Comment by shaunagm** [comment]
Yeah, that's fine.  I'll just manually revert the specific change that caused the bug.

**Pull request closed without merging**
