### PR TITLE
add instructions for building docs

### PR DESCRIPTION
**Pull request by shepardjma**
Addresses issue #425

### CODE REVIEW

**Review by rgriff23 — COMMENTED** [review]
Do we need to mention that the following packages are required (I think) to build the docs locally? Should they be added to `requirements.txt`?

```
Sphinx==1.8.3
sphinx-rtd-theme==0.4.2
m2r==0.2.1
```

See this thread: https://github.com/move-coop/parsons/pull/313#issuecomment-660397875

**Comment by shaunagm** [comment]
@rgriff23 there's two requirements.txt files, the main one, and the one in the docs folder. The contributing guide tells people to install `docs/requirements.txt` rather than listing them out.

**Review by coreyhaines — APPROVED** [review]
I ran through the instructions, and `make html` worked just fine!

Pulled down the changes, and the text shows up.

**Review by shaunagm — APPROVED** [review]
Looks good to me

**Pull request merged**
