### PR TITLE
Version bump for certain packages

### PR DESCRIPTION
**Pull request by anzelpwj**
Due to some packages found in security review, incrementing these packages in `requirements.txt`.

### CODE REVIEW

**Comment by anzelpwj** [comment]
Note with mysql-connector-python at 8.3.0 we lose connectivity to older mysql versions (5.5 and 5.6) but does get official support for Python 3.12. See https://dev.mysql.com/doc/connector-python/en/connector-python-versions.html.

**Comment by anzelpwj** [comment]
The `build` step failed due to a timeout for its installation - not sure what to do, since all the other steps passed.

https://app.circleci.com/pipelines/github/move-coop/parsons/5703/workflows/d9f6865f-585f-4d67-887a-dc53735de8b5/jobs/7289?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

**Comment by bmos** [comment]
As it says in the logs, `INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance.`

You probably just need to set google-api-core to a specific version or update some other packages that depend on it.

**Comment by bmos** [comment]
I'm also looking at updating the circleci workflow so that it uses uv which should help avoid timeouts during package resolution.
https://github.com/move-coop/parsons/pull/1122

**Comment by anzelpwj** [comment]
Sounds good @bmos - I tried pinning the google-api-core and it went ~30 minutes fussing around before timing out again. I'll await your PR getting merged in.

**Comment by bmos** [comment]
It might also be good to post about these in the Slack if you are there.

**Comment by shaunagm** [comment]
Here's the error I see on the docs-build, during the install dependencies step:
Screenshot from 2024-09-06 11-52-51

**Comment by bmos** [comment]
curlify 2.2.1 will probably solve that as it removes ">= 3" shlex version (which does not exist)

**Comment by anzelpwj** [comment]
I'll cut out the mysql upgrade for now so this isn't a breaking change. Will also pin curlify. Will that fix things? Guess we'll find out.

**Comment by anzelpwj** [comment]
Issue for upgrading `mysql-connector-python`: #1125

**Review by shaunagm — APPROVED** [review]

**Pull request merged**
