### PR TITLE
implement new hustle api call

### PR DESCRIPTION
**Pull request by nmannes**
This is my first PR, so i figured I'd do something pretty basic. I just implemented an additional API call in the Hustle module in accordance with their docs that I found in something tagged as a good first issue

- [issue](https://github.com/move-coop/parsons/issues/538)
- [api docs](https://api.hustle.com/docs/#operation/createGroupMembership)

### CODE REVIEW

**Comment by shaunagm** [comment]
Hi @nmannes! Welcome to Parsons! (Are you in the Slack? We'd love to have you)

Sorry for the delay in responding to this PR. I'm also sorry the tests didn't run automatically - I've fixed the settings so first-time contributors can still run tests. :)

From the tests, it looks like there's an issue with linting. You can follow the instructions [here](https://www.parsonsproject.org/pub/contributing-guide#linting) to fix it - let me know if you have any questions.

The only other issue is that we'll want a test for this new method. You can copy/base your test on existing tests in the [test_hustle.py file](test/test_hustle/test_hustle.py). Again, let me know if you have any questions. Writing tests can be a little confusing, especially if you're unfamiliar with mocks. We've got a guide to using mocks in tests [here](https://www.parsonsproject.org/pub/build-a-new-connector#mocking). :)

**Review by shaunagm — CHANGES_REQUESTED** [review]
:)

**Comment by shaunagm** [comment]
Hi @nmannes what's the status of this? Would you like help with the tests? Happy to do a pairing session

**Comment by nmannes** [comment]
> Hi @nmannes what's the status of this? Would you like help with the tests? Happy to do a pairing session

Hi @shaunagm! Thank you for following up. Yes, I would like to go over how to write a test for this with you. Do you have a calendly or something like that?

**Comment by shaunagm** [comment]
Yes, I do have a cal.com link - I DMed it to you on the parsons slack

**Comment by nmannes** [comment]
Update: Shauna and I spoke and there was an issue trying to generate a hustle oath2 token from sandbox credentials. Will follow up after the holidays to see why that was no good

**Review by shaunagm — APPROVED** [review]

**Comment by shaunagm** [comment]
After a bit of emailing back and forth we got credentials and were able to test this manually against a sandbox, so we're good to merge! :)

**Pull request merged**
