### PR TITLE
Improve Redshift upsert staging table column types

### PR DESCRIPTION
**Pull request by SorenSpicknall**
When a destination table already exists, this added code ensures that the staging table(s) created during a Redshfit upsert have columns that mirror those of the destination table. This helps avoid issues with copying data from table to table further on down the line.

### CODE REVIEW

**Comment by jburchard** [comment]
LGTM.

**Comment by jburchard** [comment]
Might have some conflicts with @schuyler1d PR.

**Comment by SorenSpicknall** [comment]
Yeah, I didn't realize that was merged in. These changes may not be necessary, since the behavior was handled differently in that PR. I'll likely close this PR once I've tested to ensure the case I was solving is solved by @schuyler1d's changes as well.

**Comment by schuyler1d** [comment]
fwiw, your CREATE TABLE command looks more idiomatic/better than the way I wrote it here:
https://github.com/move-coop/parsons/blob/master/parsons/databases/redshift/redshift.py#L470

maybe replace my line with yours (but use `template_table`) and then we will also have more tests.

**Comment by SorenSpicknall** [comment]
Closing this in order to make changes on another branch.

**Pull request closed without merging**
