### PR TITLE
Enable Table.to_bigquery()

### PR DESCRIPTION
**Pull request by austinweisgrau**
This creates parity with Table.to_redshift()

### CODE REVIEW

**Comment by austinweisgrau** [comment]
This is high priority for us, blocks our migration to BigQuery

**Review by Jason94 — APPROVED** [review]
This looks good to me. Approving.

Just curious, is there a reason you can't just use BigQuery.copy() instead of needing to have a Table.to_bigquery() method?

(I'm on record as saying we should deprecate and eventually get rid of the `Table.to_my_database()` methods, so I'm curious what the use case is.)

**Comment by austinweisgrau** [comment]
I use a lot of `Table.to_redshift()` and so it simplifies migration. I appreciate the method, it's simple and ergonomic. In general I think we should have parity between features in Redshift and BigQuery connectors.

Using the copy() method is fine as well in general, I have no fundamental preference at an abstract level beyond parity.

**Comment by Jason94** [comment]
> I use a lot of `Table.to_redshift()` and so it simplifies migration. I appreciate the method, it's simple and ergonomic. In general I think we should have parity between features in Redshift and BigQuery connectors.
> 
> Using the copy() method is fine as well in general, I have no fundamental preference at an abstract level beyond parity.

I agree there should be parity. Personally I'd rather delete the Redshift method than add a BigQuery one, but that's just my own battle :D Given that we can't do that anytime soon, definitely good to add the to_bigquery one in the meantime.

**Comment by austinweisgrau** [comment]
This feature seems to be included already in #938

**Comment by austinweisgrau** [comment]
Closing this out since it is included in #938

**Pull request closed without merging**
