### PR TITLE
added encoding to s3_copy function in redshift class

### PR DESCRIPTION
**Pull request by sharinetmc**

### CODE REVIEW

**Review by shaunagm — CHANGES_REQUESTED** [review]
Need to be linted by running Black but otherwise should be ready to go (relying on Willy's review in the comments)

**Comment by shaunagm** [comment]
So the instructions for how to use Black in the docs are wrong, whoops. Can you try `black --check parsons/ test/ useful_resources/`

**Comment by shaunagm** [comment]
@sharinetmc can you double-check that I resolved the merge conflict correctly and that the function does what it should? https://github.com/move-coop/parsons/pull/827/commits/0fb5ab3ee3d21e9e72a59a81e6b9ed93c1888e87

If you can confirm that, we can merge this

**Comment by sharinetmc** [comment]
@shaunagm, tests are all passing now and everything looks good!

**Review by shaunagm — APPROVED** [review]
LGTM

**Pull request merged**
