### PR TITLE
Sqlalchemy Update to  >= 1.4.22

### PR DESCRIPTION
**Pull request by matthewkrausse**
Will update the version to match the prefect reqs file. This just makes sure we can resolve a conflict and the prefect req seems to be the best way to handle sqlalchemy.

### CODE REVIEW

**Comment by matthewkrausse** [comment]
@shaunagm It looks like only two tests ran and none of the different OS builds.

**Comment by shaunagm** [comment]
Oh according to this, github actions (tests) don't run if there's a merge conflict: https://github.com/orgs/community/discussions/26304

**Comment by anzelpwj** [comment]
I think you might also want to set a version requirement in `setup.py`.

**Comment by matthewkrausse** [comment]
Deleted the wrong branch by mistake.

**Comment by matthewkrausse** [comment]
@shaunagm I think this is ready to go

**Review by shaunagm — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
