### PR TITLE
Update sqlalchemy version in requirements.txt

### PR DESCRIPTION
**Pull request by shaunagm**
At the request of @matthewkrausse (following conversation with @austinweisgrau in Slack)

### CODE REVIEW

**Comment by shaunagm** [comment]
Closing this in favor of #1050

**Comment by matthewkrausse** [comment]
> Closing this in favor of #1050

I created #1050 in order to test the tests. It seems like it didn't run any of them?

**Comment by shaunagm** [comment]
Give it a few minutes, sometimes it takes a little while to run. But yeah, if it doesn't run the tests at all I'll try and debug.

Happy to merge your PR instead of this one. The change was your idea to begin with.

**Comment by shaunagm** [comment]
Nevermind, the tests aren't running because there's a merge conflict. (let's move this discussion to the open PR though)

**Pull request closed without merging**
