### PR TITLE
SFTP SSH

### PR DESCRIPTION
**Pull request by angloyna**

### CODE REVIEW

**Comment by eliotst** [comment]
@angloyna Did you mean to close this PR?

**Comment by angloyna** [comment]
Oh yes, temporarily. I can bring it back up soon if it’s okay to add ssh to this paramiko wrapper

**Comment by eliotst** [comment]
Pardon my ignorance, but can you explain what you mean by "add ssh"..? I thought paramiko was itself an SSH client.

**Comment by angloyna** [comment]
Oh sorry it must have been too early in the morning when I responded. I was hoping to add the option to authenticate with a private rsa key in lieu or in addition to a password.

**Comment by angloyna** [comment]
oh good. I'll reopen soon

**Pull request closed without merging**
