### PR TITLE
chore(Geocoder): Add more informative error handling to geocode #729

### PR DESCRIPTION
**Pull request by talevy42**
Updates documentation and improves error handling

### CODE REVIEW

**Comment by talevy42** [comment]
For issue #729

**Comment by retacg** [comment]
Thanks for this Tal!! Where did you find that list of column names? Your documentation comment led me to go seek out the source docs for census geocoder which i believe is this: https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf

It does look like the fields listed in parsons are wrong but they aren't exactly what you changed them to either. 
Screen Shot 2023-04-24 at 11 03 40 AM

**Comment by talevy42** [comment]
I actually did it with a bit of trial and error, but the key issue is actually in the `censusgeocode` package, which is also incompletely documented. Here's the relevant line of code:

https://github.com/fitnr/censusgeocode/blob/master/src/censusgeocode/censusgeocode.py#L197

**Comment by retacg** [comment]
WOW ok thank you for doing that digging!

**Comment by mkrausse-ggtx** [comment]
I have a function I use using pandas for common address field mapping. We could refactor it for use here. 

def map_columns(df):
      # Create a list of common address column names
      address_columns = ['address', 'Address', 'ADDRESS', 'street', 'Street', 'STREET', 'addr', 'Addr', 'ADDR', 'location', 
      'Location', 'LOCATION', 'addr1']
      city_columns = ['city', 'City', 'CITY']
      state_columns = ['state', 'State', 'STATE']
      zip_columns = ['zip', 'Zip', 'ZIP', 'zip code', 'Zip Code', 'ZIP CODE', 'zipcode', 'Zipcode', 'ZIPCODE', 'ZIP5', 'zip5', 'Zip5']
  
      # Create a dictionary of column names and their corresponding common name
      address_dict = {k: 'address' for k in address_columns}
      city_dict = {k: 'city' for k in city_columns}
      state_dict = {k: 'state' for k in state_columns}
      zip_dict = {k: 'zip' for k in zip_columns}
  
      # Create a dictionary of all the dictionaries
      column_dict = {**address_dict, **city_dict, **state_dict, **zip_dict}
  
      # Rename the columns
      df.rename(columns=column_dict, inplace=True)
  
      return df`

**Review by shaunagm — APPROVED** [review]
Thank you so much for doing this digging and for fixing this! Sorry for the delay on reviewing.

**Comment by shaunagm** [comment]
> I have a function I use using pandas for common address field mapping. We could refactor it for use here.
> 

Please do submit that as a PR, or open up an issue with the code so someone else can turn it into a PR - whichever you prefer. I'd love to see Parsons get more of these helper methods.

**Pull request merged**
