### PR TITLE
Add json as allowable file type to copy_s3

### PR DESCRIPTION
**Pull request by KasiaHinkson**
Add json as allowable file type to copy_s3. Since it's converting to a Parsons table, should be no downstream effects.

### CODE REVIEW

**Review by shaunagm — APPROVED** [review]
This looks good to me, though I haven't tested it. You should merge if/when you feel it's ready.

**Comment by KasiaHinkson** [comment]
My test case failed because it's line delimited JSON, which Redshift can't handle because Redshift is a big baby, so I'll test this as soon as I can find a better test case

**Comment by KasiaHinkson** [comment]
Ok, this branch has now been tested VERY thoroughly, our Hustle sync is actively running on this branch, so I'm confident it's ready for review

**Review by sharinetmc — APPROVED** [review]
LGTM!

**Pull request merged**
