### PR TITLE
 Add support for deleting person from NGPVAN 

### PR DESCRIPTION
**Pull request by sjwmoveon**

### CODE REVIEW

**Comment by shaunagm** [comment]
@sjwmoveon is this ready for review? Did you want @crayolakat to review or someone else from the team?

Also, the tests are failing on the linting stage. You should be able to run Black to fix any issues. Instructions are here: https://move-coop.github.io/parsons/html/stable/contributing.html#linting

**Comment by sjwmoveon** [comment]
@shaunagm this is ready for review, sorry for the delay!

I actually see the build failing on the install dependencies step, with the error
`Error: [Errno 2] No such file or directory: '/home/circleci/project/venv/bin/python3'`.  Is that something I need to fix on my end or is it some kind of issue with the CI tool?

**Comment by shaunagm** [comment]
Oh sigh. That's a recurring and highly annoying CircleCI error that requires us to update the whole repository to "burst" the cache keys. I will try to get to that early next week. I believe once that's settled you'll still have the linting issue though.

**Comment by shaunagm** [comment]
Looks like the CircleCI thing is fixed, and there's another linting issue:

Screenshot from 2023-06-20 14-13-25

**Review by shaunagm — APPROVED** [review]
Looks good to me

**Comment by shaunagm** [comment]
@sjwmoveon no worries, linting is a pain! hopefully Black will make it easier for all of us

**Pull request merged**
