### PR TITLE
Remove unused function.

### PR DESCRIPTION
**Pull request by cmc333333**
This function has a typo in it (missing a comma on 329), but since it's not
referenced, we can just delete it!

### CODE REVIEW

**Comment by SorenSpicknall** [comment]
@cmc333333, in order to get past the issue with the broken build from last week, could you withdraw and resubmit this PR to allow tests to run fresh? We can rerun tests ad hoc, but not certain builds.

**Comment by cmc333333** [comment]
@SorenSpicknall : I merged in `main` to kick the build off again -- is that enough?

**Comment by shaunagm** [comment]
Looks like the checks are passing. Is this ready to approve and merge?

**Comment by cmc333333** [comment]
:+1: from me!

**Review by neverett — APPROVED** [review]
LGTM!

**Pull request merged**
